### ISSUE TITLE
Same issue here after renaming corrections

### ISSUE THREAD

**Issue by Ntemis** [FluBBaOfWard/SonSonDS#1]
linking SonSonDS.elf
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: FileHandling.o: in function `loadRoms':
/home/demetris/Desktop/Development/SonSonDS/source/FileHandling.c:248: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/SonSonDS/source/FileHandling.c:250: undefined reference to `loadFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/SonSonDS/source/FileHandling.c:258: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/SonSonDS/source/FileHandling.c:258: undefined reference to `findFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/SonSonDS/source/FileHandling.c:260: undefined reference to `loadFileWithCRC32InZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: FileHelper.o: in function `loadROM':
/home/demetris/Desktop/Development/SonSonDS/source/Shared/FileHelper.c:69: undefined reference to `loadFileTypeInZip'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/SonSonDS/source/Shared/FileHelper.c:89: undefined reference to `cenHead'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/SonSonDS/source/Shared/FileHelper.c:89: undefined reference to `zipFilename'
/opt/devkitpro/devkitARM/bin/../lib/gcc/arm-none-eabi/12.1.0/../../../../arm-none-eabi/bin/ld: /home/demetris/Desktop/Development/SonSonDS/source/Shared/FileHelper.c:89: undefined reference to `zipError'
collect2: error: ld returned 1 exit status
make[1]: *** [/opt/devkitpro/devkitARM/ds_rules:54: /home/demetris/Desktop/Development/SonSonDS/SonSonDS.elf] Error 1
make: *** [Makefile:115: build] Error 2

**Comment by FluBBaOfWard** [comment]
Pushed new source.

**Comment by Ntemis** [comment]
gtg
